### ISSUE TITLE
주소가 안들어가집니다

### ISSUE THREAD

**Issue by darwin-sj** [yf-dev/OpenCaptionsOverlay#7]
사용하기 위에서 사용법에 있는 음성인식사이트 주소로 들어갔는데 사이트에 접속이 되지 않아서 글을 남겨봅니다.
혹시 지금은 이걸 사용할수 없는건가요? 아니면 주소가 바뀐건가요?

**Comment by rishubil** [comment]
아래 링크에 공지를 보니 Twitch 계정 인증 과정이 약간 변경된 것 같습니다.

https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916/2

해당 공지를 참조하여 문제를 수정하기 전까지는 서비스를 정상적으로 사용하기 어려울 것 같습니다.
최대한 빠른 시일내에 수정해보도록 하겠습니다.

**Comment by darwin-sj** [comment]
답변 감사합니다!
잘 수정되서 다시 사용할수 있었으면 좋겠습니다.
화이팅 하세요!

**Comment by rishubil** [comment]
아마 이제 잘 동작할겁니다.
혹시 문제가 있다면 이 이슈를 다시 열어주세요.
