### ISSUE TITLE
cc-overlay.update.sh에 접속할 수 없음

### ISSUE THREAD

**Issue by harvantes4** [yf-dev/OpenCaptionsOverlay#8]
안녕하세요 방송으로 잘쓰고있는 하꼬스트리머입니다.
다름이 아니고 https://cc-overlay.update.sh/recognition 가 접속이 되지않는 문제가 있어서
이문제를 어떻게 해결해야하는지 여쭙고자 이슈에 남깁니다.

**Comment by rishubil** [comment]
안녕하세요.

현재 OpenCaptionsOverlay의 서버가 이번 태풍으로 인해 피해를 입어,
일시적으로 서비스를 제공할 수 없게 되었습니다.

아직 정확히 서버의 피해 상황을 확인할 수 없는 상황이라
정확히 언제 서비스가 복구될 수 있다 말씀드리기 어렵다는 점 양해 부탁드리겠습니다.

**Comment by rishubil** [comment]
확실한건 최소 5일 동안은 서비스를 복구하기 어렵다는 점입니다 ㅠㅠ

**Comment by rishubil** [comment]
다행히도 피해가 적은 것으로 파악되어 곧 서비스를 정상적으로 이용하실 수 있을 예정입니다.

**Comment by rishubil** [comment]
복구 작업이 완료되었습니다.
이제 정상적으로 서비스를 이용하실 수 있습니다.

혹시 계속해서 접속 장애가 발생하실 경우, 다시 이슈를 남겨주시면 감사하겠습니다.
